### ISSUE TITLE
As of MAU 4.35 calling msupdate using sudo -u fails, need to use launchctl asuser instead

### ISSUE THREAD

**Issue by sdagley** [pbowden-msft/msupdatehelper#18]
Apparently the change to XPC in MAU 4.35 causes any call to msupdate using sudo -u to fail.

User @joyrex reported on the #microsoft-autoupdate channel of the MacAdmins Slack that they were able to work around the problem by changing to launchctl asuser instead.

Change:

CMD_PREFIX="sudo -u $CONSOLE "

To:

userID=$(/usr/bin/id -u "$CONSOLE")	
CMD_PREFIX="/bin/launchctl asuser $userID "

**Comment by pbowden-msft** [comment]
Thanks for submittting the pull request Steve. Now merged into master.
