### ISSUE TITLE
Logged in user not found

### ISSUE THREAD

**Issue by mani2care** [pbowden-msft/msupdatehelper#22]
Logged in user not found canyou change this pls.

CONSOLE=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

**Comment by pbowden-msft** [comment]
Thanks for the comment. I updated the script to remove the dependency on python. See latest commit.
