### ISSUE TITLE
Add Microsoft Teams & MAU

### ISSUE THREAD

**Issue by maburdett** [pbowden-msft/msupdatehelper#8]
Starting with Version 16.21, Microsoft Teams will be installed by default for new installations.  Will MAU now update teams?  Can the script be updated to update Microsoft Teams?  Can it be updated to update MAU too?

**Comment by pbowden-msft** [comment]
Hi @maburdett ....a couple of answers:
1. MAU currently has very limited support for updating Teams. While we do register Teams with MAU is the new BusinessPro installer, right now, MAU is acting as an 'emergency patch' mechanism and not the primary method of updating Teams. So, right now, you can't fully rely on MAU to keep Teams up-to-date.
2. I'm working on a new version of the script that will also keep MAU up-to-date. It also solves several other issues such as:
- Focus is stolen from apps when msupdate is invoked
- Only one app (e.g.) Word gets updated when the helper runs
- Dynamic support for 2016 and 2019 MAU id's.
